### PR TITLE
models/H4-PLUS.yml: add new model

### PR DESCRIPTION
**Pull request by macpijan**

### CODE REVIEW

**Comment by macpijan** [comment]
@filipleple According to Dawid, it (`flash probe`) does not work correctly. Dawid mentioned some problem with relay, so take a look if relay is being controlled as expected.

**Comment by filipleple** [comment]
@macpijan  Technically the changes work and the script manages to do what it's told to do, but the probe doesn't detect any flash chip. Relay state does change to 1 during probe execution ( verified via `cat /sys/class/gpio/gpio199/value`, plus an audible "click" ), and can be manipulated at will via `osfv_cli rel`, same for the power button control. I've reseated the Pomona clip a couple of times and made sure it grips firmly, to no avail.

**Comment by macpijan** [comment]
> Relay state does change to 1 during probe execution

Shouldn't it change to LOW instead? For this platform, the power should be removed when flashing. So either the config or the code, or the HW setup (?) may be wrong here?

**Review by filipleple — CHANGES_REQUESTED** [review]
@macpijan  works with `flashing_power_state: "OFF"`

```
(venv) flewinski in ~/workstation/odroid/osfv-scripts/osfv_cli on odroid-h4 ● λ osfv_cli rte --rte_ip 19
2.168.10.214 flash probe
/home/flewinski/workstation/odroid/venv/lib/python3.11/site-packages/paramiko/pkey.py:100: CryptographyD
eprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES
 and will be removed from this module in 48.0.0.
  "cipher": algorithms.TripleDES,
/home/flewinski/workstation/odroid/venv/lib/python3.11/site-packages/paramiko/transport.py:259: Cryptogr
aphyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.Trip
leDES and will be removed from this module in 48.0.0.
  "class": algorithms.TripleDES,
DUT model retrieved from snipeit: H4-PLUS
Using rte command is invasive action, checking first if the device is not used...
Asset 153 is already checked out by you
Probing flash...
Executing command: flashrom -p linux_spi:dev=/dev/spidev1.0,spispeed=16000
flashrom v1.3.0 on Linux 5.4.69 (armv7l)
flashrom is free software, get the source code at https://flashrom.org

Using clock_gettime for delay loops (clk_id: 1, resolution: 1ns).
Found Winbond flash chip "W25Q128.V..M" (16384 kB, SPI) on linux_spi.
No operations were specified.
Since the asset 153 has been checkout manually by you prior running this script, it will NOT be checked in automatically. Please return the device when work is finished.
```

**Review by filipleple — APPROVED** [review]

**Comment by macpijan** [comment]
Thanks @filipleple , bumped version and tagged this version

**Comment by pietrushnic** [comment]
@macpijan I would have to do it manually as part of training. Do we have any write-up based on which I could create materials explaining what the correctTM theory of operation is?

**Pull request merged**
